In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [10]:
from tensorflow.keras import Sequential
from tensorflow.python.keras import regularizers
from tensorflow.keras.layers import Dense,Dropout
from tensorflow.keras import Sequential
from tensorflow.python.keras import regularizers
from tensorflow.keras.layers import Dense,Dropout,Activation,MaxPooling2D,Flatten,Conv2D,BatchNormalization
from tensorflow import keras

In [74]:
model = Sequential() 
model.add(Dense(8,input_shape = (8,),activation="relu"))
model.add(Dense(units = 10,activation= "relu"))
model.add(Dense(units = 1,activation= "sigmoid"))

In [75]:
model.summary()

Model: "sequential_11"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_30 (Dense)            (None, 8)                 72

 dense_31 (Dense)            (None, 10)                90

 dense_32 (Dense)            (None, 1)                 11

=================================================================
Total params: 173
Trainable params: 173
Non-trainable params: 0
_________________________________________________________________

In [76]:
df = pd.read_csv("D:\Downloads\DataSet\ionosphere.csv")
df.head()

   1  0  0.99539  -0.05889  0.85243  0.02306  0.83398  ...  0.21266  -0.34090  0.42267  -0.54487  0.18641  -0.45300  g
0  1  0  1.00000  -0.18829  0.93035 -0.36156 -0.10868  ... -0.19040  -0.11593 -0.16626  -0.06288 -0.13738  -0.02447  b
1  1  0  1.00000  -0.03365  1.00000  0.00485  1.00000  ...  0.43100  -0.17365  0.60436  -0.24180  0.56045  -0.38238  g
2  1  0  1.00000  -0.45161  1.00000  1.00000  0.71216  ...  1.00000  -0.20099  0.25682   1.00000 -0.32382   1.00000  b
3  1  0  1.00000  -0.02401  0.94140  0.06531  0.92106  ...  0.02431  -0.62197 -0.05707  -0.59573 -0.04608  -0.65697  g
4  1  0  0.02337  -0.00592 -0.09924 -0.11949 -0.00763  ... -0.07859   0.00732  0.00000   0.00000 -0.00039   0.12011  b

[5 rows x 35 columns]

In [11]:
df.describe()

                1      0     0.99539    -0.05889  ...     0.42267    -0.54487     0.18641    -0.45300
count  350.000000  350.0  350.000000  350.000000  ...  350.000000  350.000000  350.000000  350.000000
mean     0.891429    0.0    0.640330    0.044667  ...    0.352313   -0.002248    0.349829    0.015816
std      0.311546    0.0    0.498059    0.442032  ...    0.572289    0.513491    0.523339    0.468338
min      0.000000    0.0   -1.000000   -1.000000  ...   -1.000000   -1.000000   -1.000000   -1.000000
25%      1.000000    0.0    0.471517   -0.065388  ...    0.000000   -0.239347    0.000000   -0.161013
50%      1.000000    0.0    0.870795    0.016700  ...    0.446875    0.000000    0.413115    0.000000
75%      1.000000    0.0    1.000000    0.194727  ...    0.859490    0.200935    0.816778    0.172105
max      1.000000    0.0    1.000000    1.000000  ...    1.000000    1.000000    1.000000    1.000000

[8 rows x 34 columns]

In [16]:
df['0'].value_counts().sum()

350

In [15]:
df.shape

(350, 35)

In [20]:
X = df.drop(['1','0','g'],axis =1 )

In [21]:
X.head()

   0.99539  -0.05889  0.85243  0.02306  0.83398  -0.37708  ...  0.21266  -0.34090  0.42267  -0.54487  0.18641  -0.45300
0  1.00000  -0.18829  0.93035 -0.36156 -0.10868  -0.93597  ... -0.19040  -0.11593 -0.16626  -0.06288 -0.13738  -0.02447
1  1.00000  -0.03365  1.00000  0.00485  1.00000  -0.12062  ...  0.43100  -0.17365  0.60436  -0.24180  0.56045  -0.38238
2  1.00000  -0.45161  1.00000  1.00000  0.71216  -1.00000  ...  1.00000  -0.20099  0.25682   1.00000 -0.32382   1.00000
3  1.00000  -0.02401  0.94140  0.06531  0.92106  -0.23255  ...  0.02431  -0.62197 -0.05707  -0.59573 -0.04608  -0.65697
4  0.02337  -0.00592 -0.09924 -0.11949 -0.00763  -0.11824  ... -0.07859   0.00732  0.00000   0.00000 -0.00039   0.12011

[5 rows x 32 columns]

In [22]:
y = df['g']

In [24]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [25]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((280, 32), (70, 32), (280,), (70,))

In [26]:
y_test = y_test.replace(['g','b'],[0,1])
y_train = y_train.replace(['g','b'],[0,1])

In [77]:
model = Sequential() 
model.add(Dense(8,input_shape = (32,),activation="relu"))
model.add(Dense(units = 10,kernel_regularizer=regularizers.l2(0.01),activation= "relu"))
model.add(Dense(units = 16,activation= "relu"))
model.add(Dense(units = 1,activation= "sigmoid"))

In [78]:
model.summary()

Model: "sequential_12"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_33 (Dense)            (None, 8)                 264

 dense_34 (Dense)            (None, 10)                90

 dense_35 (Dense)            (None, 16)                176

 dense_36 (Dense)            (None, 1)                 17

=================================================================
Total params: 547
Trainable params: 547
Non-trainable params: 0
_________________________________________________________________

In [89]:
model.compile(optimizer="sgd",metrics=['accuracy'],loss = 'binary_crossentropy')

In [90]:
model.fit(X_train,y_train,batch_size=8,epochs=20,verbose=1,validation_data=(X_test,y_test))

Epoch 1/20
35/35 [==============================] - 1s 23ms/step - loss: 1.3734 - accuracy: 0.8929 - val_loss: 0.3031 - val_accuracy: 0.8857
Epoch 2/20
35/35 [==============================] - 0s 3ms/step - loss: 1.0397 - accuracy: 0.9143 - val_loss: 0.3054 - val_accuracy: 0.8857
Epoch 3/20
35/35 [==============================] - 0s 2ms/step - loss: 1.0393 - accuracy: 0.9179 - val_loss: 0.3112 - val_accuracy: 0.8857
Epoch 4/20
35/35 [==============================] - 0s 3ms/step - loss: 1.1492 - accuracy: 0.9107 - val_loss: 0.3191 - val_accuracy: 0.9000
Epoch 5/20
35/35 [==============================] - 0s 2ms/step - loss: 1.0926 - accuracy: 0.9107 - val_loss: 0.3105 - val_accuracy: 0.8857
Epoch 6/20
35/35 [==============================] - 0s 2ms/step - loss: 1.3398 - accuracy: 0.9071 - val_loss: 0.3162 - val_accuracy: 0.9000
Epoch 7/20
35/35 [==============================] - 0s 2ms/step - loss: 0.9783 - accuracy: 0.9179 - val_loss: 0.3067 - val_accuracy: 0.8857
Epoch 8/20
35/35 [==============================] - 0s 3ms/step - loss: 1.1955 - accuracy: 0.9071 - val_loss: 0.3129 - val_accuracy: 0.9000
Epoch 9/20
35/35 [==============================] - 0s 2ms/step - loss: 1.3338 - accuracy: 0.9071 - val_loss: 0.3128 - val_accuracy: 0.8857
Epoch 10/20
35/35 [==============================] - 0s 3ms/step - loss: 1.3072 - accuracy: 0.8964 - val_loss: 0.2977 - val_accuracy: 0.9143
Epoch 11/20
35/35 [==============================] - 0s 2ms/step - loss: 1.0878 - accuracy: 0.9071 - val_loss: 0.3042 - val_accuracy: 0.9143
Epoch 12/20
35/35 [==============================] - 0s 3ms/step - loss: 1.1227 - accuracy: 0.9179 - val_loss: 0.3071 - val_accuracy: 0.9143
Epoch 13/20
35/35 [==============================] - 0s 2ms/step - loss: 1.0107 - accuracy: 0.9214 - val_loss: 0.3074 - val_accuracy: 0.9143
Epoch 14/20
35/35 [==============================] - 0s 2ms/step - loss: 1.2720 - accuracy: 0.9071 - val_loss: 0.3084 - val_accuracy: 0.9143
Epoch 15/20
35/35 [==============================] - 0s 3ms/step - loss: 1.2908 - accuracy: 0.9036 - val_loss: 0.3073 - val_accuracy: 0.9143
Epoch 16/20
35/35 [==============================] - 0s 2ms/step - loss: 1.2928 - accuracy: 0.9036 - val_loss: 0.3149 - val_accuracy: 0.9286
Epoch 17/20
35/35 [==============================] - 0s 3ms/step - loss: 1.5054 - accuracy: 0.8929 - val_loss: 0.3096 - val_accuracy: 0.8857
Epoch 18/20
35/35 [==============================] - 0s 2ms/step - loss: 1.2947 - accuracy: 0.9000 - val_loss: 0.2994 - val_accuracy: 0.9143
Epoch 19/20
35/35 [==============================] - 0s 2ms/step - loss: 1.2840 - accuracy: 0.9071 - val_loss: 0.3027 - val_accuracy: 0.9143
Epoch 20/20
35/35 [==============================] - 0s 2ms/step - loss: 1.0138 - accuracy: 0.9250 - val_loss: 0.2977 - val_accuracy: 0.9143

In [93]:
model.evaluate(X_train,y_train)

9/9 [==============================] - 0s 1ms/step - loss: 0.1547 - accuracy: 0.9786

[0.15470024943351746, 0.9785714149475098]

In [94]:
model.evaluate(X_test,y_test)

3/3 [==============================] - 0s 1ms/step - loss: 0.2977 - accuracy: 0.9143

[0.2977201044559479, 0.9142857193946838]

In [88]:
model.add(Dropout(0.2))

In [38]:
model = Sequential()
model.add(Conv2D(input_shape = (224,224,3), filters = 16, kernel_size = (5,5),kernel_regularizer=regularizers.l2(0.01),activation = "relu", padding = "same" ))
model.add(MaxPooling2D())
model.add(BatchNormalization())
model.add(Dropout(0.4))
model.add(Conv2D(filters = 32, kernel_size = (3,3),activation = "relu",kernel_regularizer=regularizers.l1(0.01), padding = "same" ))
model.add(Conv2D(filters = 64, kernel_size = (3,3),activation = "relu",kernel_regularizer=regularizers.l1(0.01), padding = "same" ))
# model.add(MaxPooling2D())
model.add(Dropout(0.4))
model.add(Flatten())
model.add(Dense(units = 128, activation = "relu"))
model.add(Dropout(0.5))
model.add(Dense(units = 70, activation = "softmax"))
model.summary()

Model: "sequential_31"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 conv2d_58 (Conv2D)          (None, 224, 224, 16)      1216

 max_pooling2d_56 (MaxPoolin  (None, 112, 112, 16)     0
 g2D)

 batch_normalization_32 (Bat  (None, 112, 112, 16)     64
 chNormalization)

 dropout_66 (Dropout)        (None, 112, 112, 16)      0

 conv2d_59 (Conv2D)          (None, 112, 112, 32)      4640

 conv2d_60 (Conv2D)          (None, 112, 112, 64)      18496

 dropout_67 (Dropout)        (None, 112, 112, 64)      0

 flatten_28 (Flatten)        (None, 802816)            0

 dense_55 (Dense)            (None, 128)               102760576

 dropout_68 (Dropout)        (None, 128)               0

 dense_56 (Dense)            (None, 70)                9030

=================================================================
Total params: 102,794,022
Trainable params: 102,793,990
Non-trainable params: 32
_________________________________________________________________

In [72]:
model = Sequential()
model.add(Conv2D(64, (3,3), input_shape=(224,224,3),activation='relu',kernel_regularizer=regularizers.l2(0.01))) 
model.add(Conv2D(64, (3,3), activation='relu',kernel_regularizer=regularizers.l2(0.01)))
model.add(Dropout(0.5))
model.add(Conv2D(32, (3,3), activation='relu',kernel_regularizer=regularizers.l2(0.01)))
model.add(MaxPooling2D())
model.add(Dense(units=16,activation = 'relu'))
model.add(Dropout(0.5))
model.add(Dense(units = 32, activation = 'relu'))
model.add(Flatten())
# model.add(Dense(units = 64, activation = "relu"))
model.add(Dropout(0.5))
# model.add(Dense(units = 32, activation = 'relu'))
model.add(Dense(units = 70, activation = 'softmax'))
model.summary()

Model: "sequential_58"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 conv2d_148 (Conv2D)         (None, 222, 222, 64)      1792

 conv2d_149 (Conv2D)         (None, 220, 220, 64)      36928

 dropout_150 (Dropout)       (None, 220, 220, 64)      0

 conv2d_150 (Conv2D)         (None, 218, 218, 32)      18464

 max_pooling2d_94 (MaxPoolin  (None, 109, 109, 32)     0
 g2D)

 dense_159 (Dense)           (None, 109, 109, 16)      528

 dropout_151 (Dropout)       (None, 109, 109, 16)      0

 dense_160 (Dense)           (None, 109, 109, 32)      544

 flatten_52 (Flatten)        (None, 380192)            0

 dropout_152 (Dropout)       (None, 380192)            0

 dense_161 (Dense)           (None, 70)                26613510

=================================================================
Total params: 26,671,766
Trainable params: 26,671,766
Non-trainable params: 0
_________________________________________________________________

In [ ]:
model.compile(optimizer="")